ip=[127,0,0,1]
port="8080"
password.Raw = "test"

[driver.Demo]
printme="line printed from toml"

[web_cam]
path="/dev/video0"

[[peripherals]]
name="demo"
per.Demo.infocmd = "here"

[[peripherals]]
name="demo2"
per.Demo.infocmd = "here again"
